### ISSUE TITLE
build effectue mm si pas en premiere pos

### ISSUE THREAD

**Issue by lgrandco** [0xmamoud/minishell#3]
![image](https://github.com/0xmamoud/minishell/assets/108620622/62443fc5-46fc-45b2-9ad0-50f52517fd37)
![image](https://github.com/0xmamoud/minishell/assets/108620622/4938332e-ea2a-47ca-a3d9-ba08454d7aff)
![image](https://github.com/0xmamoud/minishell/assets/108620622/7f19cfd6-38bc-42f7-9f76-93dfdce2bcf0)

**Comment by 0xmamoud** [comment]
good
