### ISSUE TITLE
cmd vide (infile etc.)| cmd

### ISSUE THREAD

**Issue by lgrandco** [0xmamoud/minishell#4]
![image](https://github.com/0xmamoud/minishell/assets/108620622/cba124db-9613-43f5-a4ca-1561b00ce2d2)
![image](https://github.com/0xmamoud/minishell/assets/108620622/8e8d495d-8f4a-417d-8045-8301c85f8b00)
![image](https://github.com/0xmamoud/minishell/assets/108620622/03dfa25d-d98a-4865-8590-97c132d9d389)
![image](https://github.com/0xmamoud/minishell/assets/108620622/87bcfdf9-d770-4e38-9074-f535eaceebcf)

**Comment by 0xmamoud** [comment]
done
