### ISSUE TITLE
erreur creation fichier 

### ISSUE THREAD

**Issue by lgrandco** [0xmamoud/minishell#6]
![image](https://github.com/0xmamoud/minishell/assets/108620622/ef7de0f2-68c4-4b0d-98c1-37d6627cb33a)
![image](https://github.com/0xmamoud/minishell/assets/108620622/0077229e-54f6-4296-b07f-7d8aceabb83b)

**Comment by 0xmamoud** [comment]
good

**Comment by 0xmamoud** [comment]
done
